print ("flask is used to create APIs")
print ("flask is used to create APIs1")
print ("flask is used to create APIs2")
print ("flask is used to create APIs3")
print ("Route")
print ("Route1")
print ("Route3")
